### ISSUE TITLE
Discrepancies in `Behaviour` vocab

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#70]
The code list at https://vocab.ices.dk/services/pox/GetCodeList/Behaviour shows some discrepancies with the two lists it is based on:

- official publication
- extra codes assigned by ESAS https://esas-docs.ices.dk/tables/#behaviour

Comparison:

- [x] `0 Unknown`: not in source lists. Why not empty value? _not linked to ESAS, ignore_
- [x] `30-39`: ok, matches with two source lists _linked to ESAS_
- [x] `40 Scaveging`: **TYPO**, should be `Scavenging`, otherwise ok.
- [x] `41 Scaveging at fishing vessel` **TYPO**, should be `Scavenging at fishing vessel`, otherwise ok.
- [x] `42-69`: ok, matches with two source lists _linked to ESAS_
- [x] `70-88`: **will be handled, see https://github.com/ices-tools-dev/esas/issues/70#issuecomment-1073776966** matches with two source lists, but all descriptions have prepended with `Cetaceans: `, which I don't think is a good idea. I think it was added because those terms have a category `Cetaceans` in the official publication, but the category `Misfortune` is not treated as such. If the category information needs to be retained, I would move it to `LongDescription`. **TODO**: write values without `Cetaceans: ` Note that `wheeling or swimming slowly` should be written `Wheeling or swimming slowly` (capital W for consistency).
- [x] `89-93`: ok, matches with two source lists _linked to ESAS_
- [x] `94`: ok, unassigned in official, assigned to `Flushed (disturbance)` by ESAS _linked to ESAS_
- [x] `95-99`: ok, matches with two source lists _linked to ESAS_
- [x] `100-114`: ok, on ESAS list _linked to ESAS_
- [x] `115 On water/swimming`: was `1` in ESAS, now resolved. **Should be linked to ESAS**
- [x] `116`: ok, on ESAS list _linked to ESAS_
- [x] `117 Flying (no specification)`: was `4 Flying` in ESAS, now resolved. **Should be linked to ESAS**
- [x] `118 Submerged`: was `5 Completely submerged (marine mammals)` in ESAS, now resolved. **Should be linked to ESAS**
- [x] `119 Surfacing`: cetacean code. was `6 Breaking surface (marine mammals)` in ESAS, now resolved. **Should be linked to ESAS**
- [x] `120 On artificial piece of something (platform, pole)`: was `7` in ESAS, now resolved. **Should be linked to ESAS**
- [x] `121-123`: ok, on ESAS list _linked to ESAS_
- [x] `124 Not recorded`: not in source lists. Similar to unknown. _not linked to ESAS, ignore_
- [x] `127 Travelling`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [x] `128 Feeding/foraging`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [x] `129 Cooperative foraging`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [x] `130 Logging/resting`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [x] `131 Vessel avoidance`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [x] `132 Bowriding`: not in source lists. Why this code/description? _not linked to ESAS, ignore_
- [ ] `135 Flushing`: not used by ESAS, 114 is used instead.
- [x] `112 Diving (no specification)`: Was `2 Diving` in ESAS, now resolved.

@nicolasvanermen can you provide insight?

**Comment by cmspinto** [comment]
@peterdesmet a code group like [Behaviour](http://vocab.ices.dk/?ref=1709) is shared between several datasets. So not all the codes for that code group can be used by ESAS. They need to be linked to ESAS like this: 
![image](https://user-images.githubusercontent.com/8705477/159223007-4c065360-3e28-4c79-b42a-4f7b65f69a7f.png)

Currently our vocabulary is not filtering the codes that are available for each dataset, but this feature is coming this summer.

I think that when the link only takes you to the codes available for that dataset then it will be much more clear to the submitter what codes are linked with each dataset and which ones are not. 

Looks to me that most of your questions are related with that, you didn't notice that that code is not part of the ESAS dataset. But I will let one of the data managers check it and correct me if I'm mistaken.

**Comment by peterdesmet** [comment]
@carlos that answers some of the questions, but not all. See unchecked items above, mainly:

- Typos or consistency in writing values
- Codes that were created end of 2021, likely for ESAS, but that are 1) given a different code than in ESAS and 2) not linked to ESAS.

**Comment by pcrjoana** [comment]
@peterdesmet The "Cetaceans" prefix on codes 70-88 will be removed. This has been agreed in the vocabulary group, we just haven't gotten to it yet.

The codes 118, 119 and 124-132 are used in the cetaceans dataset.

We can fix the typos when we remove the "Cetaceans" prefix on codes 70-88.

**Comment by peterdesmet** [comment]
Thanks @pcrjoana. Code 119 might be useful for the ESAS dataset (where we currently have `6 Breaking surface (marine mammals)` to, but want to confirm with @nicolasvanermen .

**Comment by nicolasvanermen** [comment]
Actually, both codes 118 & 119 are used in the ESAS database!

**Comment by Osanna123** [comment]
fixed, will be online tomorrow

**Comment by peterdesmet** [comment]
Thanks, have unchecked the boxes and reopened issue until this change is live.

**Comment by peterdesmet** [comment]
Great to see this solved 👍

**Comment by nicolasvanermen** [comment]
not yet resolved
- [ ]  135 Flushing: not used by ESAS, 114 is used instead.
Code 135 should thus be deleted.

**Comment by peterdesmet** [comment]
Note that 135 Flushing is not linked to ESAS, maybe it is a term used by another database at ICES?

**Comment by nicolasvanermen** [comment]
No it was one of the 7 activity codes that were merged with behaviour.
